// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pubsub.proto

#include "pubsub.pb.h"
#include "pubsub.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace pubsub {

static const char* PubSub_method_names[] = {
  "/pubsub.PubSub/Subscribe",
  "/pubsub.PubSub/Publish",
};

std::unique_ptr< PubSub::Stub> PubSub::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PubSub::Stub> stub(new PubSub::Stub(channel, options));
  return stub;
}

PubSub::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Subscribe_(PubSub_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Publish_(PubSub_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::pubsub::Message>* PubSub::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::pubsub::SubscriptionRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::pubsub::Message>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void PubSub::Stub::async::Subscribe(::grpc::ClientContext* context, const ::pubsub::SubscriptionRequest* request, ::grpc::ClientReadReactor< ::pubsub::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::pubsub::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::pubsub::Message>* PubSub::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::pubsub::SubscriptionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pubsub::Message>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::pubsub::Message>* PubSub::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::pubsub::SubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pubsub::Message>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::Status PubSub::Stub::Publish(::grpc::ClientContext* context, const ::pubsub::PublishRequest& request, ::pubsub::PublishResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pubsub::PublishRequest, ::pubsub::PublishResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Publish_, context, request, response);
}

void PubSub::Stub::async::Publish(::grpc::ClientContext* context, const ::pubsub::PublishRequest* request, ::pubsub::PublishResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pubsub::PublishRequest, ::pubsub::PublishResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Publish_, context, request, response, std::move(f));
}

void PubSub::Stub::async::Publish(::grpc::ClientContext* context, const ::pubsub::PublishRequest* request, ::pubsub::PublishResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Publish_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pubsub::PublishResponse>* PubSub::Stub::PrepareAsyncPublishRaw(::grpc::ClientContext* context, const ::pubsub::PublishRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pubsub::PublishResponse, ::pubsub::PublishRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Publish_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pubsub::PublishResponse>* PubSub::Stub::AsyncPublishRaw(::grpc::ClientContext* context, const ::pubsub::PublishRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPublishRaw(context, request, cq);
  result->StartCall();
  return result;
}

PubSub::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PubSub_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PubSub::Service, ::pubsub::SubscriptionRequest, ::pubsub::Message>(
          [](PubSub::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pubsub::SubscriptionRequest* req,
             ::grpc::ServerWriter<::pubsub::Message>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PubSub_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PubSub::Service, ::pubsub::PublishRequest, ::pubsub::PublishResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PubSub::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pubsub::PublishRequest* req,
             ::pubsub::PublishResponse* resp) {
               return service->Publish(ctx, req, resp);
             }, this)));
}

PubSub::Service::~Service() {
}

::grpc::Status PubSub::Service::Subscribe(::grpc::ServerContext* context, const ::pubsub::SubscriptionRequest* request, ::grpc::ServerWriter< ::pubsub::Message>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PubSub::Service::Publish(::grpc::ServerContext* context, const ::pubsub::PublishRequest* request, ::pubsub::PublishResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pubsub

